site_name: Yearn Finance Omnibus
repo_url: 'https://github.com/iearn-finance/docs'
copyright: |
  Copyright &copy; 2020 <a href="https://yearn.finnace"  target="_blank" rel="noopener">yearn.finnace - All Rights Reserved</a>

extra:
  latest_version_warning:
    url_contains: /latest/
    text: 'You are reading the latest documentation for the Yearn Finance'
  support:
    chat: 
    email: 
    website: https://www.yearn.finnace.com
    issues: https://github.com/iearn-finance/docs#issues
  google_analytics:
  - ''
  - ''

nav:
  - Home: index.md
  - developers:
    - developers/code-repositories.md
    - developers/deployed-contracts-registry.md
    - developers/integration-guide.md
    - developers/misc-resources
    - developers/naming-convention.md
    - developers/yvaults-documentation

  - how-to-guides:
    - docs/README.md
    - docs/how-to-guides/how-to-add-a-custom-token-to-metamask.md
    - docs/how-to-guides/how-to-make-a-yip.md
    - docs/how-to-guides/how-to-mint-yusd.md
    - docs/how-to-guides/how-to-participate-in-a-yvault.md
    - docs/how-to-guides/how-to-understand-crv-vote-locking.md
    - docs/how-to-guides/how-to-understand-yvault-roi.md
    - docs/how-to-guides/how-to-withdraw-from-yEarn-and-yVaults.md

  - products:
    - products/earn.md
    - products/ygift.md
    - products/yinsure.md
    - products/yvaults.md
    - products/zap.md

  - r-and-d:
    - r-and-d/delegated-funding-dao-vaults.md
    - r-and-d/stablecredit.md
    - r-and-d/yborrow.md
    - r-and-d/yliquidate.md
    - r-and-d/yswap.md
    - r-and-d/ytrade.md
 
docs_dir: docs

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - tabs
  icon:
    logo: 'material/earth'
 # favicon: 'img/logo-notext.svg'
  palette:
    primary: 'blue-grey'
    accent: 'green'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
plugins:
  - search
extra_css: ["extra.css"]


markdown_extensions:
  - codehilite
  - markdown.extensions.toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: ""
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - pymdownx.betterem:
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - markdown.extensions.footnotes:
  - markdown.extensions.md_in_html:
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
        - name: pycon3
          lang: pycon
          options:
            python3: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.inline_mathjax_format
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.arithmatex:
  - pymdownx.mark:
  - pymdownx.striphtml:
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.details:
  - pymdownx.tabbed:

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/iearn-finance
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/fr8
    - icon: fontawesome/brands/intercom
      link: https://intercom.help

plugins:
  - search
  - git-revision-date-localized
  - minify:
      minify_html: true